name: Build Windows EXE with Docker

on: [push]

jobs:
  build-windows:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Windows EXE with Docker
        run: |
          docker run --rm -v "$(pwd):/src/" cdrx/pyinstaller-windows:python3.7 \
            pyinstaller --clean --onefile --noconsole --icon=app.ico main.py
      
      - name: Upload EXE
        uses: actions/upload-artifact@v4.6.2
        with:
          name: main-windows
          path: ./dist/*.exe
