name: Python Package

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.7
      uses: Qwerty-133/python-setup@v1.0.1
      with:
        python-version: '3.7'
        use-cache: false
    - name: package
      run: |
        pip install pyinstaller
        pyinstaller --onefile --noconsole --icon=app.ico main.py
    - name: Upload EXE
      uses: actions/upload-artifact@v4.6.2
      with:
        name: main
        path: ./**/*.exe
