name: Python Package

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: package
      run: |
        pip install pyinstaller
        pyinstaller --clean --onefile --noconsole --icon=app.ico main.py
    - name: Upload EXE
      uses: actions/upload-artifact@v4.6.2
      with:
        name: main
        path: ./**/*.exe
